---
title: "Garmin Index BPM vs GG Balance 0604"
author: "Jose A, Hernandez"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_download: true
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, root.dir = '~/dev/bp_hx/')
```

```{r libraries, echo=FALSE}
library(tidyverse)              # R packages designed for data science
                                # ggplot2, for data visualization
                                # dplyr, for data manipulation
                                # tidyr, for data tidying
                                # readr, for data import
                                # purrr, for functional programming
                                # tibble, for tibbles, a modern re-imagining of data frames
                                # stringr, for strings
                                # forcats, for factors
library(mcr)                    # for Deming Regression and Bland-Altman Plots
library(BlandAltmanLeh)         # for Deming Regression and Bland-Altman Plots
library(DescTools)              # for Measure of Accuracy
library(knitr)                  # for report generation
library(skimr)                  # Compact and Flexible Summaries of Data
library(gridExtra)              # Miscellaneous Functions for "Grid" Graphics
library(ggthemes)               # for even more plotting themes

```

```{r data, echo=FALSE}

bp = read.csv("~/dev/bp_hx/data/bp_hx.csv")
bp = na.omit(bp)

```

## Summary Statistics

```{r stats, echo=FALSE}

#--- Calculate n, mean, st.dev., c.v.

bp_stats = bp %>%
  dplyr::select(systolic_index_bpm,	diastolic_index_bpm, hr_index_bpm,
                systolic_gg_0604,	diastolic_gg_0604,	hr_gg_0604) %>%
  pivot_longer(cols = c('systolic_index_bpm','systolic_gg_0604',
                        'diastolic_index_bpm', 'diastolic_gg_0604',
                        'hr_index_bpm', 'hr_gg_0604'),
               names_to = "parameter_device",
               values_to = "value") %>%
  group_by(parameter_device) %>%
  summarise(
    n = n(),
    Mean = mean(value, na.rm = TRUE),
    "Std. Dev." = sd(value, na.rm = TRUE),
    Median = median(value),
    Min = min(value),
    Max = max(value),
    "25% Quantile" = quantile(value, 0.25),
    "75% Quantile" = quantile(value, 0.75)
  )

```

## 1:1 Comparision

```{r 1.to.1.comparision}

#--- Blood Pressure, mm Hg

#--- Systolic

ggplot(bp, aes(x=systolic_index_bpm, y=systolic_gg_0604)) +
  geom_point(size = 2) +
  labs(title="Systolic Blood Pressure, mm Hg",
       x ="Garmin Index BPM",
       y = "GG 0604") +
  coord_fixed(ratio = 1, xlim = c(110, 140), ylim = c(110, 140)) +
  geom_abline(linetype = 2, color = "red")
  #geom_smooth(method=lm)

#--- Diastolic

ggplot(bp, aes(x=diastolic_index_bpm, y=diastolic_gg_0604)) +
  geom_point(size = 2) +
  labs(title="Diastolic Blood Pressure, mm Hg",
       x ="Garmin Index BPM",
       y = "GG 0604") +
  coord_fixed(ratio = 1, xlim = c(70, 90), ylim = c(70, 90)) +
  geom_abline(linetype = 2, color = "red")
  #geom_smooth(method=lm)

#--- Heart Rate

ggplot(bp, aes(x=hr_index_bpm, y=hr_gg_0604)) +
  geom_point(size = 2) +
  labs(title="Heart Rate, bpm",
       x ="Garmin Index BPM",
       y = "GG 0604") +
  coord_fixed(ratio = 1, xlim = c(55, 70), ylim = c(55, 70)) +
  geom_abline(linetype = 2, color = "red")
  #geom_smooth(method=lm)

```

## Passing Bablok regression and Bland-Altman plots:
  
```{r PaBa.regression, echo=FALSE}

#--- Passing Bablok regression and Blant-Altman Plots

#--- Systolic

dem.reg.s_bp = mcreg(x=bp$systolic_index_bpm,
                      y=bp$systolic_gg_0604,
                      method.reg = "PaBa",
                      mref.name = "Garmin Index BPM",
                      mtest.name = "GG 0604"
)
plot(dem.reg.s_bp,
     sub = "Systolic")
plotResiduals(dem.reg.s_bp)
plotDifference(dem.reg.s_bp)

#--- Diastolic

dem.reg.d_bp = mcreg(x=bp$diastolic_index_bpm,
                      y=bp$diastolic_gg_0604,
                      method.reg = "PaBa",
                      mref.name = "Garmin Index BPM",
                      mtest.name = "GG 0604",
                      na.rm = TRUE
)
plot(dem.reg.d_bp,
     sub = "Diastolic")
plotResiduals(dem.reg.d_bp)
plotDifference(dem.reg.d_bp)

#--- Heart Rate

dem.reg.hr_bp = mcreg(x=bp$hr_index_bpm,
                       y=bp$hr_gg_0604,
                       method.reg = "PaBa",
                       mref.name = "Garmin Index BPM",
                       mtest.name = "GG 0604",
                       na.rm = TRUE
)
plot(dem.reg.hr_bp,
     sub = "Heart Rate")
plotResiduals(dem.reg.hr_bp)
plotDifference(dem.reg.hr_bp)

```

## Accuracy Metrics

```{r metrics, echo=FALSE}

#--- Calculate MAE, MAPE, RMSE, R2

#--- diastolic

sys_n = length(bp$systolic_index_bpm[!is.na(bp$systolic_index_bpm)])
sys_mae = MAE(bp$systolic_index_bpm, bp$systolic_gg_0604, na.rm = TRUE)
sys_mape = MAPE(bp$systolic_index_bpm, bp$systolic_gg_0604, na.rm = TRUE)
sys_rmse = RMSE(bp$systolic_index_bpm, bp$systolic_gg_0604, na.rm = TRUE)
sys_r2 = summary(lm(bp$systolic_gg_0604 ~ bp$systolic_index_bpm))$r.squared

#--- Diastolic

dia_n = length(bp$diastolic_index_bpm[!is.na(bp$diastolic_index_bpm)])
dia_mae = MAE(bp$diastolic_index_bpm, bp$diastolic_gg_0604, na.rm = TRUE)
dia_mape = MAPE(bp$diastolic_index_bpm, bp$diastolic_gg_0604, na.rm = TRUE)
dia_rmse = RMSE(bp$diastolic_index_bpm, bp$diastolic_gg_0604, na.rm = TRUE)
dia_r2 = summary(lm(bp$diastolic_gg_0604 ~ bp$diastolic_index_bpm))$r.squared

#--- Heart Rate

hr_n = length(bp$hr_index_bpm[!is.na(bp$hr_index_bpm)])
hr_mae = MAE(bp$hr_index_bpm, bp$hr_gg_0604, na.rm = TRUE)
hr_mape = MAPE(bp$hr_index_bpm, bp$hr_gg_0604, na.rm = TRUE)
hr_rmse = RMSE(bp$hr_index_bpm, bp$hr_gg_0604, na.rm = TRUE)
hr_r2 = summary(lm(bp$hr_gg_0604 ~ bp$hr_index_bpm))$r.squared

table.1 = matrix(c(sys_n,sys_mae,sys_mape,sys_rmse,sys_r2,
                   dia_n,dia_mae,dia_mape,dia_rmse,dia_r2,
                   hr_n,hr_mae,hr_mape,hr_rmse,hr_r2
)
,ncol= 5
,byrow = TRUE)
colnames(table.1) = c("n", "MAE", "MAPE","RMSE", "R2")
rownames(table.1) = c("Systolic, mm Hg", "Diastolic, mm Hg", "HR, BPM")

table.1 = kable(table.1, digits = 3, caption = "Blood Pressure Accuracy Metrics" )
table.1

````